/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package frame;

import br.com.parg.viacep.ViaCEP;
import br.com.parg.viacep.ViaCEPException;
import connection.JdbcConnection;
import entity.Cliente;
import entity.Gruporota;
import java.awt.Desktop;
import java.awt.event.KeyEvent;
import java.io.File;
import java.io.FileNotFoundException;
import java.math.BigDecimal;
import java.sql.Connection;
import java.sql.SQLException;
import java.util.List;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.persistence.EntityManager;
import javax.persistence.EntityManagerFactory;
import javax.persistence.Persistence;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import util.CNPJ;
import util.CPF;
import util.JasperService;
import util.LimpaTela;
import util.Utilitarios;

/**
 *
 * @author Jefson
 */
public class JframeClientes extends javax.swing.JFrame {

    JframeListaClientes l;

    /**
     * Creates new form JframeClientes
     */
    public JframeClientes() {
        initComponents();
        Utilitarios util = new Utilitarios();
        util.InserirIcon(this);
        util.InserirTitulo(this);

        emf = Persistence.createEntityManagerFactory("TCC_JPAPU");
        em = emf.createEntityManager();
//        this.radioFisica.setSelected(true);
        this.txtCPF.setEditable(false);
        this.btnHistorico.setVisible(false);

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        bindingGroup = new org.jdesktop.beansbinding.BindingGroup();

        rotaPUEntityManager = java.beans.Beans.isDesignTime() ? null : javax.persistence.Persistence.createEntityManagerFactory("TCC_JPAPU").createEntityManager();
        municipioQuery = java.beans.Beans.isDesignTime() ? null : rotaPUEntityManager.createQuery("SELECT m FROM Municipio m");
        municipioList = java.beans.Beans.isDesignTime() ? java.util.Collections.emptyList() : municipioQuery.getResultList();
        gruporotaQuery = java.beans.Beans.isDesignTime() ? null : rotaPUEntityManager.createQuery("SELECT g FROM Gruporota g");
        gruporotaList = java.beans.Beans.isDesignTime() ? java.util.Collections.emptyList() : gruporotaQuery.getResultList();
        TCC_JPAPUEntityManager = java.beans.Beans.isDesignTime() ? null : javax.persistence.Persistence.createEntityManagerFactory("TCC_JPAPU").createEntityManager();
        UFQuery = java.beans.Beans.isDesignTime() ? null : TCC_JPAPUEntityManager.createQuery("SELECT m.munestado FROM Municipio m GROUP BY m.munestado");
        municipioList1 = java.beans.Beans.isDesignTime() ? java.util.Collections.emptyList() : UFQuery.getResultList();
        tabbeListaClientes = new javax.swing.JTabbedPane();
        jPanel5 = new javax.swing.JPanel();
        jLabel19 = new javax.swing.JLabel();
        txtCodigo = new javax.swing.JTextField();
        jLabel20 = new javax.swing.JLabel();
        txtRazao1 = new javax.swing.JTextField();
        btnPesquisar = new javax.swing.JButton();
        btnImprimir = new javax.swing.JButton();
        btnNovo = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        tblClientes = new javax.swing.JTable();
        Cadastro_cliente = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        lblCliId = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        txtContrato = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        ComboBoxRota = new javax.swing.JComboBox<>();
        btnGravar = new javax.swing.JButton();
        btnHistorico = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        txtRazao = new javax.swing.JTextField();
        txtFantasia = new javax.swing.JTextField();
        jPanel3 = new javax.swing.JPanel();
        radioFisica = new javax.swing.JRadioButton();
        radioJuridica = new javax.swing.JRadioButton();
        jLabel7 = new javax.swing.JLabel();
        ComboBoxCidade = new javax.swing.JComboBox<>();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        txtBairro = new javax.swing.JTextField();
        txtLatitude = new javax.swing.JTextField();
        txtLongitude = new javax.swing.JTextField();
        jLabel12 = new javax.swing.JLabel();
        ComboBoxUF = new javax.swing.JComboBox<>();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        txtEndereco = new javax.swing.JTextField();
        txtNumero = new javax.swing.JTextField();
        txtEmail = new javax.swing.JTextField();
        jPanel4 = new javax.swing.JPanel();
        jLabel16 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        txtFixo = new javax.swing.JTextField();
        txtExcedente = new javax.swing.JTextField();
        txtQtde = new javax.swing.JTextField();
        txtFone = new javax.swing.JFormattedTextField();
        jLabel22 = new javax.swing.JLabel();
        forCep = new javax.swing.JFormattedTextField();
        txtCPF = new javax.swing.JFormattedTextField();
        btnNovo1 = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();
        jLabel21 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
        });

        tabbeListaClientes.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tabbeListaClientesMouseClicked(evt);
            }
        });

        jPanel5.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        jLabel19.setText("Cod.:");

        jLabel20.setText("Razão:");

        btnPesquisar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/Pesquisa_32.png"))); // NOI18N
        btnPesquisar.setText("Pesquisar");
        btnPesquisar.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        btnPesquisar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPesquisarActionPerformed(evt);
            }
        });

        btnImprimir.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/Imprimir_32.png"))); // NOI18N
        btnImprimir.setText("Imprimir");
        btnImprimir.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        btnImprimir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnImprimirActionPerformed(evt);
            }
        });

        btnNovo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/Novo_cliente_32.png"))); // NOI18N
        btnNovo.setText("Novo");
        btnNovo.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        btnNovo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnNovoActionPerformed(evt);
            }
        });

        tblClientes.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Código", "NUMERO CONTRATO", "ROTA DESCRICAO", "Razão", "Fantasia", "CPF/CNPJ", "Cidade", "UF", "TIPO", "BAIRRO", "FONE", "LATITUDE", "LONGITUDE", "NUMERO", "ENDERECO", "EMAIL", "VALORFIXO", "VALOREXCEDENTE", "QTDECONTRATADA"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tblClientes.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tblClientesMouseClicked(evt);
            }
        });
        jScrollPane2.setViewportView(tblClientes);
        if (tblClientes.getColumnModel().getColumnCount() > 0) {
            tblClientes.getColumnModel().getColumn(1).setMinWidth(0);
            tblClientes.getColumnModel().getColumn(1).setPreferredWidth(0);
            tblClientes.getColumnModel().getColumn(1).setMaxWidth(0);
            tblClientes.getColumnModel().getColumn(2).setMinWidth(0);
            tblClientes.getColumnModel().getColumn(2).setPreferredWidth(0);
            tblClientes.getColumnModel().getColumn(2).setMaxWidth(0);
            tblClientes.getColumnModel().getColumn(7).setMinWidth(0);
            tblClientes.getColumnModel().getColumn(7).setPreferredWidth(0);
            tblClientes.getColumnModel().getColumn(7).setMaxWidth(0);
            tblClientes.getColumnModel().getColumn(8).setMinWidth(0);
            tblClientes.getColumnModel().getColumn(8).setPreferredWidth(0);
            tblClientes.getColumnModel().getColumn(8).setMaxWidth(0);
            tblClientes.getColumnModel().getColumn(9).setMinWidth(0);
            tblClientes.getColumnModel().getColumn(9).setPreferredWidth(0);
            tblClientes.getColumnModel().getColumn(9).setMaxWidth(0);
            tblClientes.getColumnModel().getColumn(10).setMinWidth(0);
            tblClientes.getColumnModel().getColumn(10).setPreferredWidth(0);
            tblClientes.getColumnModel().getColumn(10).setMaxWidth(0);
            tblClientes.getColumnModel().getColumn(11).setMinWidth(0);
            tblClientes.getColumnModel().getColumn(11).setPreferredWidth(0);
            tblClientes.getColumnModel().getColumn(11).setMaxWidth(0);
            tblClientes.getColumnModel().getColumn(12).setMinWidth(0);
            tblClientes.getColumnModel().getColumn(12).setPreferredWidth(0);
            tblClientes.getColumnModel().getColumn(12).setMaxWidth(0);
            tblClientes.getColumnModel().getColumn(13).setMinWidth(0);
            tblClientes.getColumnModel().getColumn(13).setPreferredWidth(0);
            tblClientes.getColumnModel().getColumn(13).setMaxWidth(0);
            tblClientes.getColumnModel().getColumn(14).setMinWidth(0);
            tblClientes.getColumnModel().getColumn(14).setPreferredWidth(0);
            tblClientes.getColumnModel().getColumn(14).setMaxWidth(0);
            tblClientes.getColumnModel().getColumn(15).setMinWidth(0);
            tblClientes.getColumnModel().getColumn(15).setPreferredWidth(0);
            tblClientes.getColumnModel().getColumn(15).setMaxWidth(0);
            tblClientes.getColumnModel().getColumn(16).setMinWidth(0);
            tblClientes.getColumnModel().getColumn(16).setPreferredWidth(0);
            tblClientes.getColumnModel().getColumn(16).setMaxWidth(0);
            tblClientes.getColumnModel().getColumn(17).setMinWidth(0);
            tblClientes.getColumnModel().getColumn(17).setPreferredWidth(0);
            tblClientes.getColumnModel().getColumn(17).setMaxWidth(0);
            tblClientes.getColumnModel().getColumn(18).setMinWidth(0);
            tblClientes.getColumnModel().getColumn(18).setPreferredWidth(0);
            tblClientes.getColumnModel().getColumn(18).setMaxWidth(0);
        }

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel19, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtCodigo, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel20)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtRazao1, javax.swing.GroupLayout.DEFAULT_SIZE, 500, Short.MAX_VALUE)
                .addGap(18, 18, 18)
                .addComponent(btnPesquisar, javax.swing.GroupLayout.PREFERRED_SIZE, 127, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnImprimir, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnNovo, javax.swing.GroupLayout.PREFERRED_SIZE, 95, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(54, 54, 54))
            .addComponent(jScrollPane2, javax.swing.GroupLayout.Alignment.TRAILING)
        );

        jPanel5Layout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {btnImprimir, btnNovo});

        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel19)
                            .addComponent(txtCodigo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel20)
                            .addComponent(txtRazao1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addComponent(btnPesquisar, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnImprimir, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnNovo, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 402, Short.MAX_VALUE)
                .addContainerGap())
        );

        tabbeListaClientes.addTab("LISTA DE CLIENTES", jPanel5);

        Cadastro_cliente.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        jLabel1.setText("Cod.:");

        lblCliId.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblCliId.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        jLabel2.setText("Num. Contrato:");

        jLabel3.setText("Rota:");

        ComboBoxRota.setEditable(true);

        org.jdesktop.beansbinding.ELProperty eLProperty = org.jdesktop.beansbinding.ELProperty.create("${resultList}");
        org.jdesktop.swingbinding.JComboBoxBinding jComboBoxBinding = org.jdesktop.swingbinding.SwingBindings.createJComboBoxBinding(org.jdesktop.beansbinding.AutoBinding.UpdateStrategy.READ_WRITE, gruporotaQuery, eLProperty, ComboBoxRota);
        bindingGroup.addBinding(jComboBoxBinding);

        btnGravar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/Salvar_32.png"))); // NOI18N
        btnGravar.setText("Gravar");
        btnGravar.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        btnGravar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnGravarActionPerformed(evt);
            }
        });

        btnHistorico.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/historico_32.png"))); // NOI18N
        btnHistorico.setText("Historico");
        btnHistorico.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        btnHistorico.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnHistoricoActionPerformed(evt);
            }
        });

        jLabel4.setText("Razão:");

        jLabel5.setText("Fantasia:");

        jLabel6.setText("CPF/CNPJ:");

        jPanel3.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Tipo", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 1, 12))); // NOI18N

        radioFisica.setText("Física");
        radioFisica.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                radioFisicaActionPerformed(evt);
            }
        });

        radioJuridica.setText("Jurídica");
        radioJuridica.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                radioJuridicaActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addComponent(radioFisica)
                .addGap(18, 18, 18)
                .addComponent(radioJuridica)
                .addGap(0, 64, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(radioFisica)
                    .addComponent(radioJuridica))
                .addContainerGap())
        );

        jLabel7.setText("Cidade:");

        ComboBoxCidade.setEditable(true);

        eLProperty = org.jdesktop.beansbinding.ELProperty.create("${resultList}");
        jComboBoxBinding = org.jdesktop.swingbinding.SwingBindings.createJComboBoxBinding(org.jdesktop.beansbinding.AutoBinding.UpdateStrategy.READ_WRITE, municipioQuery, eLProperty, ComboBoxCidade);
        bindingGroup.addBinding(jComboBoxBinding);

        jLabel8.setText("Bairro:");

        jLabel9.setText("Fone:");

        jLabel10.setText("Latitude:");

        jLabel11.setText("Longitude:");

        jLabel12.setText("UF.:");

        ComboBoxUF.setEditable(true);
        ComboBoxUF.setToolTipText("");

        eLProperty = org.jdesktop.beansbinding.ELProperty.create("${resultList}");
        jComboBoxBinding = org.jdesktop.swingbinding.SwingBindings.createJComboBoxBinding(org.jdesktop.beansbinding.AutoBinding.UpdateStrategy.READ_WRITE, UFQuery, eLProperty, ComboBoxUF);
        bindingGroup.addBinding(jComboBoxBinding);

        jLabel13.setText("Endereço:");

        jLabel14.setText("Número:");

        jLabel15.setText("Email:");

        jPanel4.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Contrato", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 1, 12))); // NOI18N

        jLabel16.setText("Valor Fixo:");

        jLabel17.setText("Valor Excedente:");

        jLabel18.setText("Qtde Contratada:");

        txtFixo.setText("0,00");

        txtExcedente.setText("0,00");

        txtQtde.setText("0,00");
        txtQtde.setToolTipText("");

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel17)
                    .addComponent(jLabel16)
                    .addComponent(jLabel18))
                .addGap(23, 23, 23)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(txtExcedente, javax.swing.GroupLayout.DEFAULT_SIZE, 120, Short.MAX_VALUE)
                    .addComponent(txtFixo)
                    .addComponent(txtQtde))
                .addGap(0, 73, Short.MAX_VALUE))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel16)
                    .addComponent(txtFixo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel17)
                    .addComponent(txtExcedente, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel18)
                    .addComponent(txtQtde, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel4Layout.linkSize(javax.swing.SwingConstants.VERTICAL, new java.awt.Component[] {txtExcedente, txtFixo, txtQtde});

        try {
            txtFone.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("(##)# ####-####")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }

        jLabel22.setText("CEP:");

        try {
            forCep.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("#####-###")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }
        forCep.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                forCepKeyPressed(evt);
            }
        });

        txtCPF.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                txtCPFMouseClicked(evt);
            }
        });

        btnNovo1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/limpar_32.png"))); // NOI18N
        btnNovo1.setText("Limpa Tela");
        btnNovo1.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        btnNovo1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnNovo1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout Cadastro_clienteLayout = new javax.swing.GroupLayout(Cadastro_cliente);
        Cadastro_cliente.setLayout(Cadastro_clienteLayout);
        Cadastro_clienteLayout.setHorizontalGroup(
            Cadastro_clienteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(Cadastro_clienteLayout.createSequentialGroup()
                .addGroup(Cadastro_clienteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(Cadastro_clienteLayout.createSequentialGroup()
                        .addGap(10, 10, 10)
                        .addGroup(Cadastro_clienteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(Cadastro_clienteLayout.createSequentialGroup()
                                .addGroup(Cadastro_clienteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addGroup(Cadastro_clienteLayout.createSequentialGroup()
                                        .addGroup(Cadastro_clienteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jLabel6)
                                            .addComponent(jLabel7))
                                        .addGap(18, 18, 18))
                                    .addGroup(Cadastro_clienteLayout.createSequentialGroup()
                                        .addComponent(jLabel11, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addGap(21, 21, 21)))
                                .addGroup(Cadastro_clienteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(Cadastro_clienteLayout.createSequentialGroup()
                                        .addGroup(Cadastro_clienteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                            .addComponent(txtBairro)
                                            .addComponent(txtLatitude)
                                            .addComponent(txtLongitude, javax.swing.GroupLayout.DEFAULT_SIZE, 233, Short.MAX_VALUE)
                                            .addComponent(txtFone))
                                        .addGap(51, 51, 51)
                                        .addGroup(Cadastro_clienteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                            .addGroup(Cadastro_clienteLayout.createSequentialGroup()
                                                .addComponent(jLabel15, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addGap(18, 18, 18)
                                                .addComponent(txtEmail))
                                            .addGroup(Cadastro_clienteLayout.createSequentialGroup()
                                                .addComponent(jLabel13)
                                                .addGap(18, 18, 18)
                                                .addComponent(txtEndereco, javax.swing.GroupLayout.PREFERRED_SIZE, 267, javax.swing.GroupLayout.PREFERRED_SIZE))))
                                    .addComponent(txtNumero, javax.swing.GroupLayout.PREFERRED_SIZE, 102, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(Cadastro_clienteLayout.createSequentialGroup()
                                        .addComponent(ComboBoxCidade, javax.swing.GroupLayout.PREFERRED_SIZE, 174, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(jLabel12)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(ComboBoxUF, javax.swing.GroupLayout.PREFERRED_SIZE, 84, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(jLabel22)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(forCep, javax.swing.GroupLayout.PREFERRED_SIZE, 148, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(Cadastro_clienteLayout.createSequentialGroup()
                                        .addGap(9, 9, 9)
                                        .addComponent(txtCPF, javax.swing.GroupLayout.PREFERRED_SIZE, 149, javax.swing.GroupLayout.PREFERRED_SIZE))))
                            .addComponent(jLabel8)
                            .addGroup(Cadastro_clienteLayout.createSequentialGroup()
                                .addGroup(Cadastro_clienteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel4)
                                    .addComponent(jLabel5)
                                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(36, 36, 36)
                                .addGroup(Cadastro_clienteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(txtFantasia, javax.swing.GroupLayout.PREFERRED_SIZE, 286, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(Cadastro_clienteLayout.createSequentialGroup()
                                        .addGroup(Cadastro_clienteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                            .addGroup(Cadastro_clienteLayout.createSequentialGroup()
                                                .addComponent(lblCliId, javax.swing.GroupLayout.PREFERRED_SIZE, 67, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 86, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                .addComponent(txtContrato, javax.swing.GroupLayout.PREFERRED_SIZE, 87, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addGap(6, 6, 6))
                                            .addComponent(txtRazao, javax.swing.GroupLayout.PREFERRED_SIZE, 286, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addGap(53, 53, 53)
                                        .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(ComboBoxRota, javax.swing.GroupLayout.PREFERRED_SIZE, 225, javax.swing.GroupLayout.PREFERRED_SIZE))))))
                    .addGroup(Cadastro_clienteLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel9))
                    .addGroup(Cadastro_clienteLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel10))
                    .addGroup(Cadastro_clienteLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel14, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGroup(Cadastro_clienteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(Cadastro_clienteLayout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addGroup(Cadastro_clienteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(Cadastro_clienteLayout.createSequentialGroup()
                                .addComponent(btnNovo1, javax.swing.GroupLayout.PREFERRED_SIZE, 95, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(btnGravar)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(btnHistorico, javax.swing.GroupLayout.PREFERRED_SIZE, 82, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(Cadastro_clienteLayout.createSequentialGroup()
                        .addGap(7, 7, 7)
                        .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(40, Short.MAX_VALUE))
        );

        Cadastro_clienteLayout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {btnGravar, btnHistorico, btnNovo1});

        Cadastro_clienteLayout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {lblCliId, txtContrato});

        Cadastro_clienteLayout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {txtCPF, txtFantasia});

        Cadastro_clienteLayout.setVerticalGroup(
            Cadastro_clienteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(Cadastro_clienteLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(Cadastro_clienteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(Cadastro_clienteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addGroup(Cadastro_clienteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(Cadastro_clienteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(btnGravar, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(btnHistorico)
                                .addComponent(btnNovo1))
                            .addComponent(ComboBoxRota, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(Cadastro_clienteLayout.createSequentialGroup()
                                .addGap(8, 8, 8)
                                .addComponent(lblCliId, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(jLabel3)
                            .addComponent(jLabel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 25, Short.MAX_VALUE))
                        .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(txtContrato, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(Cadastro_clienteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(Cadastro_clienteLayout.createSequentialGroup()
                        .addGap(5, 5, 5)
                        .addGroup(Cadastro_clienteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel4)
                            .addComponent(txtRazao, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(Cadastro_clienteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel5)
                            .addComponent(txtFantasia, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(Cadastro_clienteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel6)
                            .addComponent(txtCPF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(Cadastro_clienteLayout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(26, 26, 26)
                .addGroup(Cadastro_clienteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7)
                    .addComponent(ComboBoxCidade, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel12)
                    .addComponent(ComboBoxUF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel22)
                    .addComponent(forCep, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(Cadastro_clienteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(Cadastro_clienteLayout.createSequentialGroup()
                        .addGroup(Cadastro_clienteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel8)
                            .addComponent(txtBairro, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel13)
                            .addComponent(txtEndereco, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(Cadastro_clienteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel9)
                            .addComponent(jLabel15)
                            .addComponent(txtEmail, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtFone, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(Cadastro_clienteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel10)
                            .addComponent(txtLatitude, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(Cadastro_clienteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel11)
                            .addComponent(txtLongitude, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(Cadastro_clienteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel14)
                    .addComponent(txtNumero, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(72, Short.MAX_VALUE))
        );

        Cadastro_clienteLayout.linkSize(javax.swing.SwingConstants.VERTICAL, new java.awt.Component[] {jLabel1, jLabel2, jLabel3});

        Cadastro_clienteLayout.linkSize(javax.swing.SwingConstants.VERTICAL, new java.awt.Component[] {btnGravar, btnHistorico, btnNovo1});

        Cadastro_clienteLayout.linkSize(javax.swing.SwingConstants.VERTICAL, new java.awt.Component[] {lblCliId, txtBairro, txtCPF, txtContrato, txtEmail, txtEndereco, txtFantasia, txtFone, txtLatitude, txtLongitude, txtNumero, txtRazao});

        Cadastro_clienteLayout.linkSize(javax.swing.SwingConstants.VERTICAL, new java.awt.Component[] {ComboBoxCidade, ComboBoxRota, ComboBoxUF});

        tabbeListaClientes.addTab("CADASTRO DE CLIENTES", Cadastro_cliente);

        jPanel1.setBackground(new java.awt.Color(0, 102, 0));

        jLabel21.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        jLabel21.setForeground(new java.awt.Color(255, 255, 255));
        jLabel21.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel21.setText("Cadastro de Clientes ");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jLabel21, javax.swing.GroupLayout.PREFERRED_SIZE, 228, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel21, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(tabbeListaClientes)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(tabbeListaClientes))
        );

        bindingGroup.bind();

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void radioJuridicaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_radioJuridicaActionPerformed
        this.radioFisica.setSelected(false);
        this.radioJuridica.setSelected(true);
        this.txtCPF.setEditable(true);
        if (this.radioJuridica.isSelected()) {
            txtCPF.setFormatterFactory(CNPJ.getFormat());
        } else {
            txtCPF.setText("");
        }
    }//GEN-LAST:event_radioJuridicaActionPerformed

    private void radioFisicaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_radioFisicaActionPerformed
        this.radioFisica.setSelected(true);
        this.radioJuridica.setSelected(false);
        this.txtCPF.setEditable(true);

        if (this.radioFisica.isSelected()) {
            txtCPF.setFormatterFactory(CPF.getFormat());
        } else {
            txtCPF.setText("");
        }


    }//GEN-LAST:event_radioFisicaActionPerformed

    private void btnHistoricoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnHistoricoActionPerformed
        int confirma = JOptionPane.showConfirmDialog(null, "Deseja Imprimir Relatório Histórico de Coletas", "Atenção", JOptionPane.YES_NO_OPTION);
        if (confirma == JOptionPane.YES_OPTION) {
            abrirPontoJasper_1("02");
//            abrirJrxmll("02");
        }
    }//GEN-LAST:event_btnHistoricoActionPerformed

    private void btnGravarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGravarActionPerformed
        if (this.lblCliId.getText().isEmpty()) {
            try {

                String contrato = this.txtContrato.getText().toUpperCase();
                int numcontrato = Integer.parseInt(contrato);
                int tipocad = 1;
                String razao = this.txtRazao.getText().toUpperCase();
                
                String fantasia = this.txtFantasia.getText().toUpperCase();
                String cpf = this.txtCPF.getText().toUpperCase();
                String email = this.txtEmail.getText().toLowerCase();
                String fone = this.txtFone.getText().toUpperCase();
                String endereço = this.txtEndereco.getText().toUpperCase();
                String numero = this.txtNumero.getText();
                String latitude = this.txtLatitude.getText();
                String longitude = this.txtLongitude.getText();
                String bairro = this.txtBairro.getText().toUpperCase();
                Object cidade = this.ComboBoxCidade.getSelectedItem().toString();
                Object uf = this.ComboBoxUF.getSelectedItem().toString();
                Object rotadesc = this.ComboBoxRota.getSelectedItem().toString();
                String vlr_fixo = this.txtFixo.getText().toUpperCase();
                BigDecimal vlrfixo = new BigDecimal(vlr_fixo);
                String valor_excedente = this.txtExcedente.getText().toUpperCase();
                BigDecimal valorexcedente = new BigDecimal(valor_excedente);
                String qtde_contratada = this.txtQtde.getText().toUpperCase();
                BigDecimal qtdecontratada = new BigDecimal(qtde_contratada);
                String tipo = this.radioFisica.getText();
                if (this.radioFisica.isSelected()) {
                    tipo = "0";
                } else {
                    tipo = "1";
                }
                int clitipo = Integer.parseInt(tipo);

                em.getTransaction().begin();
                Cliente cliente = new Cliente();
                cliente.setClinumerocontrato(numcontrato);
                Gruporota rota = new Gruporota();
                rota = (Gruporota) ComboBoxRota.getSelectedItem();
                cliente.setClirota(rota);
                cliente.setClitipocad(tipocad);
                cliente.setClinome(razao);
                cliente.setClirotadescricao((String) rotadesc);
                cliente.setClifantasia(fantasia);
                cliente.setClicpfcgc(cpf);
                cliente.setCliemail(email);
                cliente.setClifone(fone);
                cliente.setCliendereco(endereço);
                cliente.setClinumero(numero);
                cliente.setClibairro(bairro);
                cliente.setClicidade((String) cidade);
                cliente.setCliuf((String) uf);
                cliente.setClivalorfixo(vlrfixo);
                cliente.setClivalorexcedente(valorexcedente);
                cliente.setCliqtdecontratada(qtdecontratada);
                cliente.setClitipo(clitipo);
                cliente.setClilatitude(latitude);
                cliente.setClilongitude(longitude);

                em.persist(cliente);
                em.flush();

                JOptionPane.showMessageDialog(null, "Cadastrado com Sucesso!!");
                em.getTransaction().commit();
                new LimpaTela().LimpaTela(Cadastro_cliente);
                new LimpaTela().LimpaTela(jPanel4);
                this.lblCliId.setText("");

            } catch (Exception e) {
                JOptionPane.showMessageDialog(null, e);
                System.out.println(e);

            }

        } else {

            try {
               
                String codigo = this.lblCliId.getText().toUpperCase();
                String contrato = this.txtContrato.getText().toUpperCase();
                int numcontrato = Integer.parseInt(contrato);
                int tipocad = 1;
                String razao = this.txtRazao.getText().toUpperCase();
                String fantasia = this.txtFantasia.getText().toUpperCase();
                String cpf = this.txtCPF.getText().toUpperCase();
                String email = this.txtEmail.getText().toLowerCase();
                String fone = this.txtFone.getText().toUpperCase();
                String endereço = this.txtEndereco.getText().toUpperCase();
                String numero = this.txtNumero.getText();
                String latitude = this.txtLatitude.getText();
                String longitude = this.txtLongitude.getText();
                String bairro = this.txtBairro.getText().toUpperCase();
                Object cidade = this.ComboBoxCidade.getSelectedItem().toString();
                Object uf = this.ComboBoxUF.getSelectedItem().toString();
                Object rotadesc = this.ComboBoxRota.getSelectedItem().toString();
                String vlr_fixo = this.txtFixo.getText().toUpperCase();
                BigDecimal vlrfixo = new BigDecimal(vlr_fixo);
                String valor_excedente = this.txtExcedente.getText().toUpperCase();
                BigDecimal valorexcedente = new BigDecimal(valor_excedente);
                String qtde_contratada = this.txtQtde.getText().toUpperCase();
                BigDecimal qtdecontratada = new BigDecimal(qtde_contratada);
                String tipo = this.radioFisica.getText();
                if (this.radioFisica.isSelected()) {
                    tipo = "0";
                } else {
                    tipo = "1";
                }
                int clitipo = Integer.parseInt(tipo);

                em.getTransaction().begin();
                Cliente cliente = em.find(Cliente.class, Integer.parseInt(codigo));
                cliente.setClinumerocontrato(numcontrato);

                Gruporota rota = new Gruporota();
                rota = (Gruporota) ComboBoxRota.getSelectedItem();
                cliente.setClirota(rota);
                cliente.setClitipocad(tipocad);
                cliente.setClinome(razao);
                cliente.setClirotadescricao((String) rotadesc);
                cliente.setClifantasia(fantasia);
                cliente.setClicpfcgc(cpf);
                cliente.setCliemail(email);
                cliente.setClifone(fone);
                cliente.setCliendereco(endereço);
                cliente.setClinumero(numero);
                cliente.setClibairro(bairro);
                cliente.setClicidade((String) cidade);
                cliente.setCliuf((String) uf);
                cliente.setClivalorfixo(vlrfixo);
                cliente.setClivalorexcedente(valorexcedente);
                cliente.setCliqtdecontratada(qtdecontratada);
                cliente.setClitipo(clitipo);
                cliente.setClilatitude(latitude);
                cliente.setClilongitude(longitude);
                //salva no banco
                em.getTransaction().commit();
                //retorna o ultimo

                JOptionPane.showMessageDialog(null, "Atualizado com Sucesso!!");
                new LimpaTela().LimpaTela(Cadastro_cliente);
                new LimpaTela().LimpaTela(jPanel4);
                this.lblCliId.setText("");
                //        em.close();
            } catch (Exception e) {
                JOptionPane.showMessageDialog(null, e);
                System.out.println(e);
            }

        }


    }//GEN-LAST:event_btnGravarActionPerformed

    private void btnNovoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnNovoActionPerformed
        tabbeListaClientes.setSelectedIndex(1);
        new LimpaTela().LimpaTela(Cadastro_cliente);
        new LimpaTela().LimpaTela(jPanel4);
        this.lblCliId.setText("");


    }//GEN-LAST:event_btnNovoActionPerformed

    private void tblClientesMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblClientesMouseClicked
        tabbeListaClientes.setSelectedIndex(1);
        int linha = this.tblClientes.getSelectedRow();
        String id = this.tblClientes.getValueAt(linha, 0).toString();
        String numerocontrato = this.tblClientes.getValueAt(linha, 1).toString();
        String rotadescricao = this.tblClientes.getValueAt(linha, 2).toString();
        String nome = this.tblClientes.getValueAt(linha, 3).toString();
        String fantasia = this.tblClientes.getValueAt(linha, 4).toString();
        String cpfcgc = this.tblClientes.getValueAt(linha, 5).toString();
        String cidade = this.tblClientes.getValueAt(linha, 6).toString();
        String uf = this.tblClientes.getValueAt(linha, 7).toString();
        String tipo = this.tblClientes.getValueAt(linha, 8).toString();
        String bairro = this.tblClientes.getValueAt(linha, 9).toString();
        String fone = this.tblClientes.getValueAt(linha, 10).toString();
        String latitude = this.tblClientes.getValueAt(linha, 11).toString();
        String longitude = this.tblClientes.getValueAt(linha, 12).toString();
        String numero = this.tblClientes.getValueAt(linha, 13).toString();
        String endereco = this.tblClientes.getValueAt(linha, 14).toString();
        String email = this.tblClientes.getValueAt(linha, 15).toString();
        String valorfixo = this.tblClientes.getValueAt(linha, 16).toString();
        String valorexcedente = this.tblClientes.getValueAt(linha, 17).toString();
        String qtdecontratada = this.tblClientes.getValueAt(linha, 18).toString();

        lblCliId.setText(id);
        txtContrato.setText(numerocontrato);

        ComboBoxRota.setSelectedItem(rotadescricao);
        txtRazao.setText(nome);
        txtFantasia.setText(fantasia);
        txtCPF.setText(cpfcgc);
        ComboBoxCidade.setSelectedItem(cidade);
        ComboBoxUF.setSelectedItem(uf);
        if ("0".equals(tipo)) {
            this.radioFisica.setSelected(true);
            this.radioJuridica.setSelected(false);

        } else {
            this.radioJuridica.setSelected(true);
            this.radioFisica.setSelected(false);
        }

        txtBairro.setText(bairro);
        txtFone.setText(fone);
        txtLatitude.setText(latitude);
        txtLongitude.setText(longitude);
        txtNumero.setText(numero);
        txtEndereco.setText(endereco);
        txtEmail.setText(email);
        txtFixo.setText(valorfixo);
        txtExcedente.setText(valorexcedente);
        txtQtde.setText(qtdecontratada);
        this.btnHistorico.setVisible(true);

    }//GEN-LAST:event_tblClientesMouseClicked

    private void tabbeListaClientesMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tabbeListaClientesMouseClicked
        DefaultTableModel model = (DefaultTableModel) this.tblClientes.getModel();
        //limpa a tabela
        while (model.getRowCount() > 0) {
            model.removeRow(0);
        }
        //faz select de todos os dados e armazena em uma lista

        List clientes = em.createNamedQuery("Cliente.findByClitipocad", Cliente.class).getResultList();
        //pega todos os contato e adiciona na tebela.
        for (int i = 0; i < clientes.size(); i++) {
            model.addRow(new Object[]{
                ((Cliente) clientes.get(i)).getCliid(),
                ((Cliente) clientes.get(i)).getClinumerocontrato(),
                ((Cliente) clientes.get(i)).getClirotadescricao(),
                ((Cliente) clientes.get(i)).getClinome(),
                ((Cliente) clientes.get(i)).getClifantasia(),
                ((Cliente) clientes.get(i)).getClicpfcgc(),
                ((Cliente) clientes.get(i)).getClicidade(),
                ((Cliente) clientes.get(i)).getCliuf(),
                ((Cliente) clientes.get(i)).getClitipo(),
                ((Cliente) clientes.get(i)).getClibairro(),
                ((Cliente) clientes.get(i)).getClifone(),
                ((Cliente) clientes.get(i)).getClilatitude(),
                ((Cliente) clientes.get(i)).getClilongitude(),
                ((Cliente) clientes.get(i)).getClinumero(),
                ((Cliente) clientes.get(i)).getCliendereco(),
                ((Cliente) clientes.get(i)).getCliemail(),
                ((Cliente) clientes.get(i)).getClivalorfixo(),
                ((Cliente) clientes.get(i)).getClivalorexcedente(),
                ((Cliente) clientes.get(i)).getCliqtdecontratada()

            });
        }
    }//GEN-LAST:event_tabbeListaClientesMouseClicked

    private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened
        DefaultTableModel model = (DefaultTableModel) this.tblClientes.getModel();
        //limpa a tabela
        while (model.getRowCount() > 0) {
            model.removeRow(0);
        }
        //faz select de todos os dados e armazena em uma lista

        List clientes = em.createNamedQuery("Cliente.findByClitipocad", Cliente.class).getResultList();
        //pega todos os contato e adiciona na tebela.
        for (int i = 0; i < clientes.size(); i++) {
            model.addRow(new Object[]{
                ((Cliente) clientes.get(i)).getCliid(),
                ((Cliente) clientes.get(i)).getClinumerocontrato(),
                ((Cliente) clientes.get(i)).getClirotadescricao(),
                ((Cliente) clientes.get(i)).getClinome(),
                ((Cliente) clientes.get(i)).getClifantasia(),
                ((Cliente) clientes.get(i)).getClicpfcgc(),
                ((Cliente) clientes.get(i)).getClicidade(),
                ((Cliente) clientes.get(i)).getCliuf(),
                ((Cliente) clientes.get(i)).getClitipo(),
                ((Cliente) clientes.get(i)).getClibairro(),
                ((Cliente) clientes.get(i)).getClifone(),
                ((Cliente) clientes.get(i)).getClilatitude(),
                ((Cliente) clientes.get(i)).getClilongitude(),
                ((Cliente) clientes.get(i)).getClinumero(),
                ((Cliente) clientes.get(i)).getCliendereco(),
                ((Cliente) clientes.get(i)).getCliemail(),
                ((Cliente) clientes.get(i)).getClivalorfixo(),
                ((Cliente) clientes.get(i)).getClivalorexcedente(),
                ((Cliente) clientes.get(i)).getCliqtdecontratada()

            });
        }
    }//GEN-LAST:event_formWindowOpened

    private void forCepKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_forCepKeyPressed
        if (evt.getKeyCode() == KeyEvent.VK_ENTER) {
            ViaCEP viaCep = new ViaCEP();

            try {
                viaCep.buscar(formataDados(forCep.getText()));
                txtBairro.setText(viaCep.getBairro());
                txtEndereco.setText(viaCep.getLogradouro());
                ComboBoxUF.setSelectedItem(viaCep.getUf());
                ComboBoxCidade.setSelectedItem(viaCep.getLocalidade());
            } catch (ViaCEPException ex) {
                Logger.getLogger(JframeClientes.class.getName()).log(Level.SEVERE, null, ex);
            }
        }
        if (evt.getKeyCode() == evt.VK_ENTER) {
            txtNumero.requestFocus();
        }
    }//GEN-LAST:event_forCepKeyPressed
    private static void abrirJrxml(String numero) {

        Connection connection = JdbcConnection.connection();
        JasperService service = new JasperService();
        service.abrirJasperViewer("relatorios/Clientes-" + numero + ".jrxml", connection);
        try {
            connection.close();
        } catch (SQLException ex) {
            Logger.getLogger(JframeListaClientes.class.getName()).log(Level.SEVERE, null, ex);
        }

    }

    private void abrirJrxmll(String numero) {
        int codigo = Integer.parseInt(lblCliId.getText());
        Connection connection = JdbcConnection.connection();
        JasperService service = new JasperService();

        if (!"".equals(lblCliId.getText())) {

            service.addParams("cliid", codigo);
        }
        service.abrirJasperViewer("relatorios/Historico-" + numero + ".jrxml", connection);

        try {
            connection.close();
        } catch (SQLException ex) {
            Logger.getLogger(JframeClientes.class.getName()).log(Level.SEVERE, null, ex);
        }

    }


    private void btnImprimirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnImprimirActionPerformed
        int confirma = JOptionPane.showConfirmDialog(null, "Deseja Imprimir Relatório Clientes", "Atenção", JOptionPane.YES_NO_OPTION);
        if (confirma == JOptionPane.YES_OPTION) {

//            abrirJrxml("01");
//            exportarParaPdf("01", "C:/nlw/Relatorio de clientes.pdf");
            abrirPontoJasper("01");
        }


    }//GEN-LAST:event_btnImprimirActionPerformed

    private void btnPesquisarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPesquisarActionPerformed
        String codigo = this.txtCodigo.getText();
        String nome = this.txtRazao1.getText().toUpperCase();
        DefaultTableModel model = (DefaultTableModel) this.tblClientes.getModel();
        while (model.getRowCount() > 0) {
            model.removeRow(0);
        }

        String sql = "SELECT *FROM Cliente  WHERE 1=1 and clitipocad = 1 ";

        if (!"".equals(nome)) {
            sql += " and clinome like '%" + nome + "%'";

        }
        if (!"".equals(codigo)) {
            sql += " and cliid in (" + codigo + ")";

        }

        try {

            List<Cliente> cliente = em.createNativeQuery(sql, Cliente.class).getResultList();
            DefaultTableModel dados = (DefaultTableModel) tblClientes.getModel();
            dados.setNumRows(0);
            for (Cliente c : cliente) {
                dados.addRow(new Object[]{
                    c.getCliid(),
                    c.getClinumerocontrato(),
                    c.getClirotadescricao(),
                    c.getClinome(),
                    c.getClifantasia(),
                    c.getClicpfcgc(),
                    c.getClicidade(),
                    c.getCliuf(),
                    c.getClitipo(),
                    c.getClibairro(),
                    c.getClifone(),
                    c.getClilatitude(),
                    c.getClilongitude(),
                    c.getClinumero(),
                    c.getCliendereco(),
                    c.getCliemail(),
                    c.getClivalorfixo(),
                    c.getClivalorexcedente(),
                    c.getCliqtdecontratada()
                });

            }
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, "Usuario não encontrado");
        }
    }//GEN-LAST:event_btnPesquisarActionPerformed

    private void txtCPFMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txtCPFMouseClicked
        String tipo = "0";

        if (this.radioFisica.isSelected() || this.radioJuridica.isSelected()) {
            tipo = "1";
        } else {
            JOptionPane.showMessageDialog(rootPane, "Selecione um tipo de cliente !");
        }
    }//GEN-LAST:event_txtCPFMouseClicked

    private void btnNovo1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnNovo1ActionPerformed
        new LimpaTela().LimpaTela(Cadastro_cliente);
        new LimpaTela().LimpaTela(jPanel4);
        this.lblCliId.setText("");
    }//GEN-LAST:event_btnNovo1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(JframeClientes.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(JframeClientes.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(JframeClientes.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(JframeClientes.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new JframeClientes().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    public javax.swing.JPanel Cadastro_cliente;
    public javax.swing.JComboBox<String> ComboBoxCidade;
    public javax.swing.JComboBox<String> ComboBoxRota;
    public javax.swing.JComboBox<String> ComboBoxUF;
    private javax.persistence.EntityManager TCC_JPAPUEntityManager;
    private javax.persistence.Query UFQuery;
    private javax.swing.JButton btnGravar;
    private javax.swing.JButton btnHistorico;
    private javax.swing.JButton btnImprimir;
    private javax.swing.JButton btnNovo;
    private javax.swing.JButton btnNovo1;
    private javax.swing.JButton btnPesquisar;
    private javax.swing.JFormattedTextField forCep;
    private java.util.List<entity.Gruporota> gruporotaList;
    private javax.persistence.Query gruporotaQuery;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JScrollPane jScrollPane2;
    public javax.swing.JLabel lblCliId;
    private java.util.List<entity.Municipio> municipioList;
    private java.util.List<entity.Municipio> municipioList1;
    private javax.persistence.Query municipioQuery;
    public javax.swing.JRadioButton radioFisica;
    public javax.swing.JRadioButton radioJuridica;
    private javax.persistence.EntityManager rotaPUEntityManager;
    public javax.swing.JTabbedPane tabbeListaClientes;
    private javax.swing.JTable tblClientes;
    public javax.swing.JTextField txtBairro;
    private javax.swing.JFormattedTextField txtCPF;
    private javax.swing.JTextField txtCodigo;
    public javax.swing.JTextField txtContrato;
    public javax.swing.JTextField txtEmail;
    public javax.swing.JTextField txtEndereco;
    public javax.swing.JTextField txtExcedente;
    public javax.swing.JTextField txtFantasia;
    public javax.swing.JTextField txtFixo;
    public javax.swing.JFormattedTextField txtFone;
    public javax.swing.JTextField txtLatitude;
    public javax.swing.JTextField txtLongitude;
    public javax.swing.JTextField txtNumero;
    public javax.swing.JTextField txtQtde;
    public javax.swing.JTextField txtRazao;
    private javax.swing.JTextField txtRazao1;
    private org.jdesktop.beansbinding.BindingGroup bindingGroup;
    // End of variables declaration//GEN-END:variables

    EntityManagerFactory emf;
    EntityManager em;

    public static String formataDados(String dado) {
        dado = dado.replaceAll("\\.", "");
        dado = dado.replaceAll("-", "");
        dado = dado.replaceAll("[()]", "");
        dado = dado.replaceAll("[ ]", "");
        return dado;
    }

    private void exportarParaPdf(String numero, String saida) {
        Connection connection = JdbcConnection.connection();
        JasperService service = new JasperService();
        try {
            service.exportarParaPDF("relatorios/Clientes-" + numero + ".jrxml", connection, saida);

            File f = new File("C:\\nlw");
            try {
                if (f.mkdir()) {
                    System.out.println("Pasta criada");
                } else {
                    System.out.println("Directory is not created");
                }
            } catch (Exception e) {
                e.printStackTrace();
            }

            File file = new File("C:/nlw/Relatorio de clientes.pdf");
            try {
                Desktop.getDesktop().open(file);

            } catch (Exception e) {

                JOptionPane.showConfirmDialog(null, e);

            }
            file.deleteOnExit();

        } catch (FileNotFoundException ex) {
            Logger.getLogger(JframeClientes.class.getName()).log(Level.SEVERE, null, ex);
        }
        try {
            connection.close();
        } catch (SQLException ex) {
            Logger.getLogger(JframeListaClientes.class.getName()).log(Level.SEVERE, null, ex);
        }

    }

    private void abrirPontoJasper(String numero) {
        Connection connection = JdbcConnection.connection();
        JasperService service = new JasperService();
        service.abrirPontoJasper("relatorios/Clientes-" + numero + ".jasper", connection);
        try {
            connection.close();
        } catch (SQLException ex) {
            Logger.getLogger(JframeListaClientes.class.getName()).log(Level.SEVERE, null, ex);
        }

    }

    private void abrirPontoJasper_1(String numero) {
        int codigo = Integer.parseInt(lblCliId.getText());
        Connection connection = JdbcConnection.connection();
        JasperService service = new JasperService();

        if (!"".equals(lblCliId.getText())) {

            service.addParams("cliid", codigo);
        }
        service.abrirPontoJasper("relatorios/Historico-" + numero + ".jasper", connection);

        try {
            connection.close();
        } catch (SQLException ex) {
            Logger.getLogger(JframeClientes.class.getName()).log(Level.SEVERE, null, ex);
        }

        try {
            connection.close();
        } catch (SQLException ex) {
            Logger.getLogger(JframeListaClientes.class.getName()).log(Level.SEVERE, null, ex);
        }

    }
}
