/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package frame;

import entity.Cliente;
import entity.Rota;
import java.math.BigDecimal;
import java.text.SimpleDateFormat;
import java.util.Date;
import java.util.List;
import javax.persistence.EntityManager;
import javax.persistence.EntityManagerFactory;
import javax.persistence.Persistence;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import util.Utilitarios;

/**
 *
 * @author Jefson
 */
public class JframeInserirColeta extends javax.swing.JFrame {

    JframeColetas f;
    Date data = new Date();
    SimpleDateFormat formatador = new SimpleDateFormat("yyyy/MM/dd HH:mm:ss");

    /**
     * Creates new form JframeInserirColeta
     */
    public JframeInserirColeta() {
        initComponents();
        Utilitarios util = new Utilitarios();
        util.InserirIcon(this);
        util.InserirTitulo(this);
        emf = Persistence.createEntityManagerFactory("TCC_JPAPU");
        em = emf.createEntityManager();
        btnPesquisaMotorista.setToolTipText("Pesquisa Motorista");
        btnPesquisaVeiculo.setToolTipText("Pesquisa Veículo");
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        TCC_JPAPUEntityManager = java.beans.Beans.isDesignTime() ? null : javax.persistence.Persistence.createEntityManagerFactory("TCC_JPAPU").createEntityManager();
        clienteQuery = java.beans.Beans.isDesignTime() ? null : TCC_JPAPUEntityManager.createQuery("SELECT c FROM Cliente c WHERE c.clitipocad = 2 ORDER BY c.cliid");
        clienteList = java.beans.Beans.isDesignTime() ? java.util.Collections.emptyList() : clienteQuery.getResultList();
        veiculoQuery = java.beans.Beans.isDesignTime() ? null : TCC_JPAPUEntityManager.createQuery("SELECT v FROM Veiculo v");
        veiculoList = java.beans.Beans.isDesignTime() ? java.util.Collections.emptyList() : veiculoQuery.getResultList();
        gruporotaQuery = java.beans.Beans.isDesignTime() ? null : TCC_JPAPUEntityManager.createQuery("SELECT g FROM Gruporota g");
        gruporotaList = java.beans.Beans.isDesignTime() ? java.util.Collections.emptyList() : gruporotaQuery.getResultList();
        clienteQuery1 = java.beans.Beans.isDesignTime() ? null : TCC_JPAPUEntityManager.createQuery("SELECT c.clinome FROM Cliente c");
        clienteList1 = java.beans.Beans.isDesignTime() ? java.util.Collections.emptyList() : clienteQuery1.getResultList();
        jPanel1 = new javax.swing.JPanel();
        jLabel21 = new javax.swing.JLabel();
        InserirColeta = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        lblCodigo = new javax.swing.JLabel();
        lblRazao = new javax.swing.JLabel();
        lblFantasia = new javax.swing.JLabel();
        lblCPF = new javax.swing.JLabel();
        lblCidade = new javax.swing.JLabel();
        lblEndereco = new javax.swing.JLabel();
        lblBairo = new javax.swing.JLabel();
        lblFone = new javax.swing.JLabel();
        lblLatitude = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        lblUF = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        lblNumero = new javax.swing.JLabel();
        lblEmail = new javax.swing.JLabel();
        lblLongitude = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        lblRespnsavel = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        txtObs = new javax.swing.JTextField();
        jLabel17 = new javax.swing.JLabel();
        lblData = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        jLabel19 = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        jLabel20 = new javax.swing.JLabel();
        jLabel22 = new javax.swing.JLabel();
        jLabel23 = new javax.swing.JLabel();
        txtlValorFixo = new javax.swing.JTextField();
        txtQdtContratada = new javax.swing.JTextField();
        txtValorExcedente = new javax.swing.JTextField();
        jLabel24 = new javax.swing.JLabel();
        lblQdtExcedente = new javax.swing.JLabel();
        jLabel25 = new javax.swing.JLabel();
        lblTotal = new javax.swing.JLabel();
        btnCancelar = new javax.swing.JButton();
        btnConcluir = new javax.swing.JButton();
        btnInserir = new javax.swing.JButton();
        btnGravar = new javax.swing.JButton();
        btnReativar = new javax.swing.JButton();
        lblCodColeta = new javax.swing.JLabel();
        lblNomeStatus = new javax.swing.JLabel();
        lblStatus = new javax.swing.JLabel();
        txtQdtColetada = new javax.swing.JTextField();
        lblRotaDescricao = new javax.swing.JLabel();
        txtVeiculo = new javax.swing.JTextField();
        txtMotorista = new javax.swing.JTextField();
        btnPesquisaMotorista = new javax.swing.JButton();
        btnPesquisaVeiculo = new javax.swing.JButton();
        txtCodMotorista = new javax.swing.JTextField();
        txtCodVeiculo = new javax.swing.JTextField();
        lblrotaID = new javax.swing.JLabel();
        lblmodelo = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("JframeInserirColeta");
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
        });

        jPanel1.setBackground(new java.awt.Color(0, 102, 0));

        jLabel21.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        jLabel21.setForeground(new java.awt.Color(255, 255, 255));
        jLabel21.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel21.setText("Detalhes da Coleta");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jLabel21, javax.swing.GroupLayout.PREFERRED_SIZE, 283, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel21, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        InserirColeta.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        InserirColeta.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                InserirColetaKeyReleased(evt);
            }
        });

        jLabel1.setText("Cod.:");

        jLabel2.setText("Razão:");

        jLabel3.setText("Fantasia:");

        jLabel4.setText("CPF/CNPJ:");

        jLabel5.setText("Cidade:");

        jLabel6.setText("Endereço:");

        jLabel7.setText("Bairro:");

        jLabel8.setText("Fone:");

        jLabel9.setText("Latitude:");

        lblCodigo.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        lblCodigo.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);

        lblRazao.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        lblRazao.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);

        lblFantasia.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        lblFantasia.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);

        lblCPF.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        lblCPF.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);

        lblCidade.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        lblCidade.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);

        lblEndereco.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        lblEndereco.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);

        lblBairo.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        lblBairo.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);

        lblFone.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        lblFone.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);

        lblLatitude.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        lblLatitude.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);

        jLabel10.setText("Rota:");

        jLabel11.setText("UF:");

        lblUF.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        lblUF.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);

        jLabel13.setText("Número:");

        jLabel14.setText("E-mail:");

        jLabel15.setText("Longitude:");

        lblNumero.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        lblNumero.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);

        lblEmail.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        lblEmail.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);

        lblLongitude.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        lblLongitude.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);

        jLabel12.setText("Responsável:");

        lblRespnsavel.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        lblRespnsavel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);

        jLabel16.setText("Qtde Coletada em KG:");

        txtObs.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "OBS.:", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 1, 11))); // NOI18N

        jLabel17.setText("Data da Coleta:");

        lblData.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        lblData.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);

        jLabel18.setText("Motorista:");

        jLabel19.setText("Veículo:");

        jPanel3.setBorder(javax.swing.BorderFactory.createTitledBorder("Contrato"));

        jLabel20.setText("Valor Fixo:");

        jLabel22.setText("Qtd Contratada em Kg:");

        jLabel23.setText("Valor Excedente:");

        txtlValorFixo.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        txtlValorFixo.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txtlValorFixo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtlValorFixoActionPerformed(evt);
            }
        });

        txtQdtContratada.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        txtQdtContratada.setHorizontalAlignment(javax.swing.JTextField.CENTER);

        txtValorExcedente.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        txtValorExcedente.setHorizontalAlignment(javax.swing.JTextField.CENTER);

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(jLabel20)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 67, Short.MAX_VALUE)
                        .addComponent(txtlValorFixo, javax.swing.GroupLayout.PREFERRED_SIZE, 77, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap())
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel22)
                            .addComponent(jLabel23))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addComponent(txtValorExcedente, javax.swing.GroupLayout.PREFERRED_SIZE, 77, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addContainerGap())
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addComponent(txtQdtContratada, javax.swing.GroupLayout.PREFERRED_SIZE, 77, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(0, 0, Short.MAX_VALUE))))))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel20)
                    .addComponent(txtlValorFixo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel22)
                    .addComponent(txtQdtContratada, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel23)
                    .addComponent(txtValorExcedente, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
        );

        jLabel24.setText("Qtd Excedente:");

        lblQdtExcedente.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        lblQdtExcedente.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblQdtExcedente.setText("0");
        lblQdtExcedente.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 1, true));

        jLabel25.setText("TOTAL:");

        lblTotal.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        lblTotal.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblTotal.setText("0");
        lblTotal.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 1, true));

        btnCancelar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/Cancelar_32.png"))); // NOI18N
        btnCancelar.setText("Cancelar");
        btnCancelar.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        btnCancelar.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        btnCancelar.setHorizontalTextPosition(javax.swing.SwingConstants.RIGHT);
        btnCancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCancelarActionPerformed(evt);
            }
        });

        btnConcluir.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/Concluir.png"))); // NOI18N
        btnConcluir.setText("Concluir");
        btnConcluir.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        btnConcluir.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        btnConcluir.setHorizontalTextPosition(javax.swing.SwingConstants.RIGHT);
        btnConcluir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnConcluirActionPerformed(evt);
            }
        });

        btnInserir.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/Novo_cliente_32.png"))); // NOI18N
        btnInserir.setText("Inserir Cliente");
        btnInserir.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        btnInserir.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        btnInserir.setHorizontalTextPosition(javax.swing.SwingConstants.RIGHT);
        btnInserir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnInserirActionPerformed(evt);
            }
        });

        btnGravar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/Salvar_32.png"))); // NOI18N
        btnGravar.setText("Gravar");
        btnGravar.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        btnGravar.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        btnGravar.setHorizontalTextPosition(javax.swing.SwingConstants.RIGHT);
        btnGravar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnGravarActionPerformed(evt);
            }
        });

        btnReativar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/Reativar_32.png"))); // NOI18N
        btnReativar.setText("Reativar");
        btnReativar.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        btnReativar.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        btnReativar.setHorizontalTextPosition(javax.swing.SwingConstants.RIGHT);
        btnReativar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnReativarActionPerformed(evt);
            }
        });

        lblCodColeta.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        lblCodColeta.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblCodColeta.setBorder(javax.swing.BorderFactory.createTitledBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 1, true), "Cod.: Coleta"));

        lblNomeStatus.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        lblNomeStatus.setText("Status:");

        lblStatus.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N

        txtQdtColetada.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        txtQdtColetada.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txtQdtColetada.setText("0");
        txtQdtColetada.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 1, true));
        txtQdtColetada.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtQdtColetadaActionPerformed(evt);
            }
        });

        lblRotaDescricao.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        lblRotaDescricao.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);

        btnPesquisaMotorista.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/Pesquisa.png.png"))); // NOI18N
        btnPesquisaMotorista.setBorder(null);
        btnPesquisaMotorista.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPesquisaMotoristaActionPerformed(evt);
            }
        });

        btnPesquisaVeiculo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/Pesquisa.png.png"))); // NOI18N
        btnPesquisaVeiculo.setBorder(null);
        btnPesquisaVeiculo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPesquisaVeiculoActionPerformed(evt);
            }
        });

        txtCodVeiculo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtCodVeiculoActionPerformed(evt);
            }
        });

        lblrotaID.setFont(new java.awt.Font("Tahoma", 0, 1)); // NOI18N

        lblmodelo.setFont(new java.awt.Font("Tahoma", 0, 1)); // NOI18N

        javax.swing.GroupLayout InserirColetaLayout = new javax.swing.GroupLayout(InserirColeta);
        InserirColeta.setLayout(InserirColetaLayout);
        InserirColetaLayout.setHorizontalGroup(
            InserirColetaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(InserirColetaLayout.createSequentialGroup()
                .addComponent(txtObs, javax.swing.GroupLayout.PREFERRED_SIZE, 247, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(42, 42, 42)
                .addComponent(jLabel17)
                .addGroup(InserirColetaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(InserirColetaLayout.createSequentialGroup()
                        .addGroup(InserirColetaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(InserirColetaLayout.createSequentialGroup()
                                .addGap(193, 193, 193)
                                .addComponent(lblrotaID))
                            .addGroup(InserirColetaLayout.createSequentialGroup()
                                .addGap(321, 321, 321)
                                .addComponent(lblmodelo)))
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(InserirColetaLayout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(lblData, javax.swing.GroupLayout.PREFERRED_SIZE, 165, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
            .addGroup(InserirColetaLayout.createSequentialGroup()
                .addGap(6, 6, 6)
                .addGroup(InserirColetaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(InserirColetaLayout.createSequentialGroup()
                        .addGroup(InserirColetaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel1)
                            .addComponent(jLabel2)
                            .addComponent(jLabel3)
                            .addComponent(jLabel4)
                            .addComponent(jLabel5)
                            .addComponent(jLabel6)
                            .addComponent(jLabel7)
                            .addComponent(jLabel8)
                            .addComponent(jLabel9))
                        .addGap(25, 25, 25)
                        .addGroup(InserirColetaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblCodigo, javax.swing.GroupLayout.PREFERRED_SIZE, 61, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblRazao, javax.swing.GroupLayout.PREFERRED_SIZE, 165, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblFantasia, javax.swing.GroupLayout.PREFERRED_SIZE, 165, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblCPF, javax.swing.GroupLayout.PREFERRED_SIZE, 165, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblCidade, javax.swing.GroupLayout.PREFERRED_SIZE, 165, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblEndereco, javax.swing.GroupLayout.PREFERRED_SIZE, 165, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblBairo, javax.swing.GroupLayout.PREFERRED_SIZE, 165, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblFone, javax.swing.GroupLayout.PREFERRED_SIZE, 165, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblLatitude, javax.swing.GroupLayout.PREFERRED_SIZE, 165, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(41, 41, 41)
                        .addGroup(InserirColetaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel10)
                            .addComponent(jLabel13)
                            .addComponent(jLabel14)
                            .addComponent(jLabel11)
                            .addComponent(jLabel15))
                        .addGap(18, 18, 18)
                        .addGroup(InserirColetaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblRotaDescricao, javax.swing.GroupLayout.PREFERRED_SIZE, 165, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblNumero, javax.swing.GroupLayout.PREFERRED_SIZE, 165, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblEmail, javax.swing.GroupLayout.PREFERRED_SIZE, 165, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblUF, javax.swing.GroupLayout.PREFERRED_SIZE, 165, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblLongitude, javax.swing.GroupLayout.PREFERRED_SIZE, 165, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(InserirColetaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(InserirColetaLayout.createSequentialGroup()
                                .addGroup(InserirColetaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                    .addGroup(InserirColetaLayout.createSequentialGroup()
                                        .addComponent(jLabel16)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 42, Short.MAX_VALUE)
                                        .addComponent(txtQdtColetada, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(InserirColetaLayout.createSequentialGroup()
                                        .addGroup(InserirColetaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jLabel24)
                                            .addComponent(jLabel25))
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addGroup(InserirColetaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                            .addComponent(lblQdtExcedente, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(lblTotal, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE))))
                                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addGroup(InserirColetaLayout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(InserirColetaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, InserirColetaLayout.createSequentialGroup()
                                        .addComponent(jLabel19)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(txtCodVeiculo, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(10, 10, 10)
                                        .addComponent(txtVeiculo, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(btnPesquisaVeiculo, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(InserirColetaLayout.createSequentialGroup()
                                        .addGroup(InserirColetaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addGroup(InserirColetaLayout.createSequentialGroup()
                                                .addComponent(jLabel18)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                                .addComponent(txtCodMotorista, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addGap(7, 7, 7)
                                                .addComponent(txtMotorista, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                .addComponent(btnPesquisaMotorista, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE))
                                            .addGroup(InserirColetaLayout.createSequentialGroup()
                                                .addGap(8, 8, 8)
                                                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                        .addGap(1, 1, 1)))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGroup(InserirColetaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, InserirColetaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(btnConcluir, javax.swing.GroupLayout.PREFERRED_SIZE, 122, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(btnGravar, javax.swing.GroupLayout.PREFERRED_SIZE, 122, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(btnReativar, javax.swing.GroupLayout.PREFERRED_SIZE, 122, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(btnCancelar, javax.swing.GroupLayout.PREFERRED_SIZE, 126, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(btnInserir))
                                    .addComponent(lblCodColeta, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 108, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addContainerGap())))
                    .addGroup(InserirColetaLayout.createSequentialGroup()
                        .addGroup(InserirColetaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(InserirColetaLayout.createSequentialGroup()
                                .addComponent(lblNomeStatus)
                                .addGap(27, 27, 27)
                                .addComponent(lblStatus, javax.swing.GroupLayout.PREFERRED_SIZE, 191, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(InserirColetaLayout.createSequentialGroup()
                                .addComponent(jLabel12)
                                .addGap(12, 12, 12)
                                .addComponent(lblRespnsavel, javax.swing.GroupLayout.PREFERRED_SIZE, 165, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(711, 711, 711))))
        );

        InserirColetaLayout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {txtCodMotorista, txtCodVeiculo});

        InserirColetaLayout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {txtMotorista, txtVeiculo});

        InserirColetaLayout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {btnCancelar, btnConcluir, btnGravar, btnInserir, btnReativar, lblCodColeta});

        InserirColetaLayout.setVerticalGroup(
            InserirColetaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(InserirColetaLayout.createSequentialGroup()
                .addGap(11, 11, 11)
                .addGroup(InserirColetaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(InserirColetaLayout.createSequentialGroup()
                        .addGap(8, 8, 8)
                        .addComponent(lblNomeStatus))
                    .addComponent(lblStatus, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(19, 19, 19)
                .addGroup(InserirColetaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(InserirColetaLayout.createSequentialGroup()
                        .addGroup(InserirColetaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(InserirColetaLayout.createSequentialGroup()
                                .addGap(15, 15, 15)
                                .addComponent(lblCodColeta, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(btnConcluir, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(6, 6, 6)
                                .addComponent(btnInserir, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(6, 6, 6)
                                .addComponent(btnGravar, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(btnReativar, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(btnCancelar, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 65, Short.MAX_VALUE))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, InserirColetaLayout.createSequentialGroup()
                                .addGap(0, 0, Short.MAX_VALUE)
                                .addGroup(InserirColetaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel18)
                                    .addGroup(InserirColetaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(txtCodMotorista, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(txtMotorista, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addComponent(btnPesquisaMotorista))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(InserirColetaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(btnPesquisaVeiculo)
                                    .addGroup(InserirColetaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(txtVeiculo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(jLabel19))
                                    .addComponent(txtCodVeiculo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(18, 18, 18)
                                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(138, 138, 138)))
                        .addGroup(InserirColetaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(InserirColetaLayout.createSequentialGroup()
                                .addGap(9, 9, 9)
                                .addComponent(jLabel16))
                            .addComponent(txtQdtColetada, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(InserirColetaLayout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addGap(24, 24, 24)
                        .addComponent(jLabel2)
                        .addGap(24, 24, 24)
                        .addComponent(jLabel3)
                        .addGap(24, 24, 24)
                        .addComponent(jLabel4)
                        .addGap(24, 24, 24)
                        .addComponent(jLabel5)
                        .addGap(24, 24, 24)
                        .addComponent(jLabel6)
                        .addGap(24, 24, 24)
                        .addComponent(jLabel7)
                        .addGap(24, 24, 24)
                        .addComponent(jLabel8)
                        .addGap(24, 24, 24)
                        .addComponent(jLabel9))
                    .addGroup(InserirColetaLayout.createSequentialGroup()
                        .addComponent(lblCodigo, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(6, 6, 6)
                        .addComponent(lblRazao, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(6, 6, 6)
                        .addComponent(lblFantasia, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(6, 6, 6)
                        .addComponent(lblCPF, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(6, 6, 6)
                        .addComponent(lblCidade, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(6, 6, 6)
                        .addComponent(lblEndereco, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(6, 6, 6)
                        .addComponent(lblBairo, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(6, 6, 6)
                        .addComponent(lblFone, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(6, 6, 6)
                        .addComponent(lblLatitude, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(InserirColetaLayout.createSequentialGroup()
                        .addComponent(jLabel10)
                        .addGap(24, 24, 24)
                        .addComponent(jLabel13)
                        .addGap(24, 24, 24)
                        .addComponent(jLabel14)
                        .addGap(24, 24, 24)
                        .addComponent(jLabel11, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(167, 167, 167)
                        .addComponent(jLabel15))
                    .addGroup(InserirColetaLayout.createSequentialGroup()
                        .addComponent(lblRotaDescricao, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(6, 6, 6)
                        .addComponent(lblNumero, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(6, 6, 6)
                        .addComponent(lblEmail, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(6, 6, 6)
                        .addComponent(lblUF, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(143, 143, 143)
                        .addComponent(lblLongitude, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(3, 3, 3)
                .addGroup(InserirColetaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(InserirColetaLayout.createSequentialGroup()
                        .addGap(3, 3, 3)
                        .addGroup(InserirColetaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel12)
                            .addComponent(lblRespnsavel, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(InserirColetaLayout.createSequentialGroup()
                                .addGap(3, 3, 3)
                                .addComponent(lblQdtExcedente, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addComponent(jLabel24))
                .addGroup(InserirColetaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(InserirColetaLayout.createSequentialGroup()
                        .addGap(6, 6, 6)
                        .addGroup(InserirColetaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(InserirColetaLayout.createSequentialGroup()
                                .addGap(9, 9, 9)
                                .addComponent(txtObs, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(InserirColetaLayout.createSequentialGroup()
                                .addGap(77, 77, 77)
                                .addComponent(jLabel17))))
                    .addGroup(InserirColetaLayout.createSequentialGroup()
                        .addGroup(InserirColetaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(InserirColetaLayout.createSequentialGroup()
                                .addGap(6, 6, 6)
                                .addComponent(lblTotal, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(InserirColetaLayout.createSequentialGroup()
                                .addGap(18, 18, 18)
                                .addComponent(jLabel25)))
                        .addGap(34, 34, 34)
                        .addComponent(lblData, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(InserirColetaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(lblrotaID)
                            .addComponent(lblmodelo)))))
        );

        InserirColetaLayout.linkSize(javax.swing.SwingConstants.VERTICAL, new java.awt.Component[] {txtCodMotorista, txtCodVeiculo});

        InserirColetaLayout.linkSize(javax.swing.SwingConstants.VERTICAL, new java.awt.Component[] {txtMotorista, txtVeiculo});

        InserirColetaLayout.linkSize(javax.swing.SwingConstants.VERTICAL, new java.awt.Component[] {btnConcluir, lblCodColeta});

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(InserirColeta, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(InserirColeta, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened

        //limpa a tabela
        //faz select de todos os dados e armazena em uma lista
        List clientes = em.createNamedQuery("Cliente.findByUsuario", Cliente.class).getResultList();
        //pega todos os contato e adiciona na tebela.


    }//GEN-LAST:event_formWindowOpened

    private void btnPesquisaVeiculoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPesquisaVeiculoActionPerformed
        JframeListaVeiculo veiculo = new JframeListaVeiculo();
        veiculo.setVisible(true);
        veiculo.c = this;
        veiculo.pack();
    }//GEN-LAST:event_btnPesquisaVeiculoActionPerformed

    private void btnPesquisaMotoristaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPesquisaMotoristaActionPerformed
        JframeListaMotorista motorista = new JframeListaMotorista();
        motorista.setVisible(true);
        motorista.c = this;
        motorista.pack();
    }//GEN-LAST:event_btnPesquisaMotoristaActionPerformed

    private void btnGravarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGravarActionPerformed

        if (this.txtCodMotorista.getText().isEmpty() || this.txtCodVeiculo.getText().isEmpty()
                || this.txtMotorista.getText().isEmpty() || this.txtVeiculo.getText().isEmpty()) {
            JOptionPane.showMessageDialog(null, "Por favor Preencha os dados Motorista e Veiculos.",
                    "Atenção!", JOptionPane.WARNING_MESSAGE);
            return;

        }
        if (this.lblCodColeta.getText().isEmpty()) {

            int codigo = Integer.parseInt(lblCodigo.getText());
            String rotadescricao = lblRotaDescricao.getText();

            int codigomotorista = Integer.parseInt(txtCodMotorista.getText());

            String motorista = this.txtMotorista.getText();

            int intcodveiculo = Integer.parseInt(txtCodVeiculo.getText());

            String placa = this.txtVeiculo.getText();
            int codRotaId = Integer.parseInt(this.lblrotaID.getText());

            String nome = lblRazao.getText();
            String fantasia = lblFantasia.getText();
            String cpfcgc = lblCPF.getText();
            String cidade = lblCidade.getText();
            String obs = txtObs.getText();
            String responsavel = null;
            String uf = lblUF.getText();
            String bairro = lblBairo.getText();
            String endereco = lblEndereco.getText();
            String fone = lblFone.getText();
            String latitude = lblLatitude.getText();
            String longitude = lblLongitude.getText();
            String rotaStatus = "P";
            String tipo = "";
            String qdt = txtQdtColetada.getText();
            BigDecimal qdtKg = new BigDecimal(qdt);
            String numero = lblNumero.getText();
            String email = lblEmail.getText();
            String valorfixo = txtlValorFixo.getText();
            BigDecimal valorfx = new BigDecimal(valorfixo);
            String valorexcedente = txtValorExcedente.getText();
            BigDecimal valorexc = new BigDecimal(valorexcedente);
            String qtdecontratada = txtQdtContratada.getText();
            BigDecimal qtdecontract = new BigDecimal(qtdecontratada);
            String valortotal = lblTotal.getText();
            BigDecimal valorT = new BigDecimal(valortotal);
            String qtdExer = lblQdtExcedente.getText();
            BigDecimal qtdexedente = new BigDecimal(qtdExer);
            String veiculomodelo = lblmodelo.getText();
            try {
                em.getTransaction().begin();
                Rota rota = new Rota();
                rota.setRotagdrid(codRotaId);
                rota.setRotagdrdescricao(rotadescricao);
                rota.setRotacliid(codigo);
                rota.setRotacliidmotorista(codigomotorista);
                rota.setRotaveiid(intcodveiculo);
                rota.setRotaveiplaca(placa);
                rota.setRotaveimodelo(veiculomodelo);
                rota.setRotaclinomemotorista(motorista);
                rota.setRotaclinome(nome);
                rota.setRotaclifantasia(fantasia);
                rota.setRotaclilongitude(longitude);
                rota.setRotaclilatitude(latitude);
                rota.setRotadata(data);
                rota.setRotadatacoleta(data);
                rota.setRotastatus(rotaStatus);
                rota.setRotatipof(tipo);
                rota.setRotaqtdeexcedente(qtdexedente);
                rota.setRotaqtde(qdtKg);
                rota.setRotavalorfixo(valorfx);
                rota.setRotacliqtdecontratada(qtdecontract);
                rota.setRotavalorexcedente(valorexc);
                rota.setRotavalortotal(valorT);
                rota.setRotaobservacao(obs);
                rota.setRotaresponsavel(responsavel);
                rota.setRotaclifone(fone);
                rota.setRotacliemail(email);
                rota.setRotaclicpfcgc(cpfcgc);
                rota.setRotacliendereco(endereco);
                rota.setRotaclibairro(bairro);
                rota.setRotaclinumero(numero);
                rota.setRotaclicidade(cidade);
                rota.setRotacliuf(uf);

                em.persist(rota);
                em.flush();
                JOptionPane.showMessageDialog(null, "Cadastrado com Sucesso!!");
                em.getTransaction().commit();

               
                

            } catch (Exception e) {
                JOptionPane.showMessageDialog(null, e);

            }

        } else {
            String codRota = lblCodColeta.getText();

            String obs = txtObs.getText();

            String qdt = txtQdtColetada.getText();
            BigDecimal qdtKg = new BigDecimal(qdt);

            String valorfixo = txtlValorFixo.getText();
            BigDecimal valorfx = new BigDecimal(valorfixo);
            String valorexcedente = txtValorExcedente.getText();
            BigDecimal valorexc = new BigDecimal(valorexcedente);
            String qtdecontratada = txtQdtContratada.getText();
            BigDecimal qtdecontract = new BigDecimal(qtdecontratada);
            String valortotal = lblTotal.getText();
            BigDecimal valorT = new BigDecimal(valortotal);
            String qtdExer = lblQdtExcedente.getText();
            BigDecimal qtdexedente = new BigDecimal(qtdExer);
            String veiculomodelo = lblmodelo.getText();

            int codigomotorista = Integer.parseInt(txtCodMotorista.getText());

            String motorista = this.txtMotorista.getText();

            int intcodveiculo = Integer.parseInt(txtCodVeiculo.getText());

            String placa = this.txtVeiculo.getText();

            try {
                em.getTransaction().begin();
                Rota rota = em.find(Rota.class, Integer.parseInt(codRota));

                rota.setRotacliidmotorista(codigomotorista);
                rota.setRotaveiid(intcodveiculo);
                rota.setRotaveiplaca(placa);
                rota.setRotaveimodelo(veiculomodelo);
                rota.setRotaclinomemotorista(motorista);
                rota.setRotaqtdeexcedente(qtdexedente);
                rota.setRotaqtde(qdtKg);
                rota.setRotavalorfixo(valorfx);
                rota.setRotacliqtdecontratada(qtdecontract);
                rota.setRotavalorexcedente(valorexc);
                rota.setRotavalortotal(valorT);
                rota.setRotaobservacao(obs);
                em.getTransaction().commit();

                JOptionPane.showMessageDialog(null, "Atualizado com Sucesso!!");

          

               
            } catch (Exception e) {
                JOptionPane.showMessageDialog(null, e);

            }

        }
        
                dispose();

               
    }//GEN-LAST:event_btnGravarActionPerformed

    private void btnInserirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnInserirActionPerformed
        JframeListaClientes cliente = new JframeListaClientes();
        cliente.setVisible(true);
        cliente.c = this;
        cliente.pack();

    }//GEN-LAST:event_btnInserirActionPerformed

    private void txtlValorFixoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtlValorFixoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtlValorFixoActionPerformed

    private void InserirColetaKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_InserirColetaKeyReleased

    }//GEN-LAST:event_InserirColetaKeyReleased

    private void txtQdtColetadaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtQdtColetadaActionPerformed
        double valorExer = 0;
        double valorTotal = 0;
        double valorFixo = Double.parseDouble(txtlValorFixo.getText());

        double qdtExer = 0;

        double qtdContradata = Double.parseDouble(txtQdtContratada.getText());
        double valorExedente = Double.parseDouble(txtValorExcedente.getText());
        double qtdColetada = Double.parseDouble(txtQdtColetada.getText());

        //String convmargemLucro= formatador.convertVigulaParaPonto(margemLucro);
        if (qtdColetada > qtdContradata) {

            qdtExer = qtdColetada - qtdContradata;
            valorExer = valorExedente * qdtExer;
            valorTotal = valorFixo + valorExer;
            String qdtexe = Double.toString(qdtExer);
            String vlrtotal = Double.toString(valorTotal);
            lblQdtExcedente.setText(qdtexe);
            lblTotal.setText(vlrtotal);

        } else {

        }

//        String qdtexe = Double.toString(qdtExer);
//        String vlrtotal = Double.toString(valorTotal);
//        lblQdtExcedente.setText(qdtexe);
//        lblTotal.setText(vlrtotal);

    }//GEN-LAST:event_txtQdtColetadaActionPerformed

    private void txtCodVeiculoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtCodVeiculoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtCodVeiculoActionPerformed

    private void btnReativarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnReativarActionPerformed

        int codRota = Integer.parseInt(lblCodColeta.getText());

        String rotaStatus = "P";
        String tipo = "";
        String qdt = txtQdtColetada.getText();
        BigDecimal qdtKg = new BigDecimal(qdt);
        String numero = lblNumero.getText();
        String email = lblEmail.getText();
        String valorfixo = txtlValorFixo.getText();
        BigDecimal valorfx = new BigDecimal(valorfixo);
        String valorexcedente = txtValorExcedente.getText();
        BigDecimal valorexc = new BigDecimal(valorexcedente);
        String qtdecontratada = txtQdtContratada.getText();
        BigDecimal qtdecontract = new BigDecimal(qtdecontratada);
        String valortotal = lblTotal.getText();
        BigDecimal valorT = new BigDecimal(valortotal);
        String qtdExer = lblQdtExcedente.getText();
        BigDecimal qtdexedente = new BigDecimal(qtdExer);
        String veiculomodelo = lblmodelo.getText();
        int codigo = Integer.parseInt(lblCodigo.getText());
        String rotadescricao = lblRotaDescricao.getText();

        int codigomotorista = Integer.parseInt(txtCodMotorista.getText());

        String motorista = this.txtMotorista.getText();

        int intcodveiculo = Integer.parseInt(txtCodVeiculo.getText());

        String placa = this.txtVeiculo.getText();
        int codRotaId = Integer.parseInt(this.lblrotaID.getText());
        try {
            em.getTransaction().begin();
            Rota rota = em.find(Rota.class, (codRota));

            rota.setRotastatus(rotaStatus);

            em.getTransaction().commit();
            System.out.println(rota.getRotaid());
            JOptionPane.showMessageDialog(null, "Reativado com Sucesso!!");

            f.atualizaTabela();
            dispose();

        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, e);

        }

    }//GEN-LAST:event_btnReativarActionPerformed

    private void btnCancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCancelarActionPerformed
        int codRota = Integer.parseInt(lblCodColeta.getText());

        String rotaStatus = "C";
        String tipo = "";
        String qdt = txtQdtColetada.getText();
        BigDecimal qdtKg = new BigDecimal(qdt);
        String numero = lblNumero.getText();
        String email = lblEmail.getText();
        String valorfixo = txtlValorFixo.getText();
        BigDecimal valorfx = new BigDecimal(valorfixo);
        String valorexcedente = txtValorExcedente.getText();
        BigDecimal valorexc = new BigDecimal(valorexcedente);
        String qtdecontratada = txtQdtContratada.getText();
        BigDecimal qtdecontract = new BigDecimal(qtdecontratada);
        String valortotal = lblTotal.getText();
        BigDecimal valorT = new BigDecimal(valortotal);
        String qtdExer = lblQdtExcedente.getText();
        BigDecimal qtdexedente = new BigDecimal(qtdExer);
        String veiculomodelo = lblmodelo.getText();
        int codigo = Integer.parseInt(lblCodigo.getText());
        String rotadescricao = lblRotaDescricao.getText();

        int codigomotorista = Integer.parseInt(txtCodMotorista.getText());

        String motorista = this.txtMotorista.getText();

        int intcodveiculo = Integer.parseInt(txtCodVeiculo.getText());

        String placa = this.txtVeiculo.getText();
        int codRotaId = Integer.parseInt(this.lblrotaID.getText());
        int mensagem = JOptionPane.showConfirmDialog(this, "Deseja cancelar essa coleta?", "Cancelar Coleta",
                JOptionPane.YES_NO_OPTION, JOptionPane.WARNING_MESSAGE);
        if (mensagem == JOptionPane.YES_OPTION) {
            try {
                em.getTransaction().begin();
                Rota rota = em.find(Rota.class, (codRota));

                rota.setRotastatus(rotaStatus);

                em.getTransaction().commit();
                JOptionPane.showMessageDialog(null, "Cancelado com Sucesso");
                System.out.println(rota.getRotaid());
                f.atualizaTabela();
                dispose();

            } catch (Exception e) {
                JOptionPane.showMessageDialog(null, e);

            }
        }
    }//GEN-LAST:event_btnCancelarActionPerformed

    private void btnConcluirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnConcluirActionPerformed
        String codRota = lblCodColeta.getText();

        String rotaStatus = "M";

        String obs = txtObs.getText();

        String qdt = txtQdtColetada.getText();
        BigDecimal qdtKg = new BigDecimal(qdt);

        String valorfixo = txtlValorFixo.getText();
        BigDecimal valorfx = new BigDecimal(valorfixo);
        String valorexcedente = txtValorExcedente.getText();
        BigDecimal valorexc = new BigDecimal(valorexcedente);
        String qtdecontratada = txtQdtContratada.getText();
        BigDecimal qtdecontract = new BigDecimal(qtdecontratada);
        String valortotal = lblTotal.getText();
        BigDecimal valorT = new BigDecimal(valortotal);
        String qtdExer = lblQdtExcedente.getText();
        BigDecimal qtdexedente = new BigDecimal(qtdExer);
        String veiculomodelo = lblmodelo.getText();

        int codigomotorista = Integer.parseInt(txtCodMotorista.getText());

        String motorista = this.txtMotorista.getText();

        int intcodveiculo = Integer.parseInt(txtCodVeiculo.getText());

        String placa = this.txtVeiculo.getText();

        try {
            em.getTransaction().begin();
            Rota rota = em.find(Rota.class, Integer.parseInt(codRota));

            rota.setRotacliidmotorista(codigomotorista);
            rota.setRotaveiid(intcodveiculo);
            rota.setRotaveiplaca(placa);
            rota.setRotaveimodelo(veiculomodelo);
            rota.setRotaclinomemotorista(motorista);
            rota.setRotaqtdeexcedente(qtdexedente);
            rota.setRotaqtde(qdtKg);
            rota.setRotastatus(rotaStatus);
            rota.setRotavalorfixo(valorfx);
            rota.setRotacliqtdecontratada(qtdecontract);
            rota.setRotavalorexcedente(valorexc);
            rota.setRotavalortotal(valorT);
            rota.setRotaobservacao(obs);
            rota.setRotadata(data);
            rota.setRotadatacoleta(data);
            em.getTransaction().commit();

            JOptionPane.showMessageDialog(null, "Atualizado com Sucesso!!");
            DefaultTableModel modelo = (DefaultTableModel) this.f.tblColetas.getModel();
            modelo.setNumRows(0);
            f.atualizaTabela();
            dispose();
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, e);

        }
    }//GEN-LAST:event_btnConcluirActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(JframeInserirColeta.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(JframeInserirColeta.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(JframeInserirColeta.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(JframeInserirColeta.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new JframeInserirColeta().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel InserirColeta;
    private javax.persistence.EntityManager TCC_JPAPUEntityManager;
    public javax.swing.JButton btnCancelar;
    public javax.swing.JButton btnConcluir;
    public javax.swing.JButton btnGravar;
    public javax.swing.JButton btnInserir;
    public javax.swing.JButton btnPesquisaMotorista;
    public javax.swing.JButton btnPesquisaVeiculo;
    public javax.swing.JButton btnReativar;
    private java.util.List<entity.Cliente> clienteList;
    private java.util.List<entity.Cliente> clienteList1;
    private javax.persistence.Query clienteQuery;
    private javax.persistence.Query clienteQuery1;
    private java.util.List<entity.Gruporota> gruporotaList;
    private javax.persistence.Query gruporotaQuery;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel25;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel3;
    public javax.swing.JLabel lblBairo;
    public javax.swing.JLabel lblCPF;
    public javax.swing.JLabel lblCidade;
    public javax.swing.JLabel lblCodColeta;
    public javax.swing.JLabel lblCodigo;
    public javax.swing.JLabel lblData;
    public javax.swing.JLabel lblEmail;
    public javax.swing.JLabel lblEndereco;
    public javax.swing.JLabel lblFantasia;
    public javax.swing.JLabel lblFone;
    public javax.swing.JLabel lblLatitude;
    public javax.swing.JLabel lblLongitude;
    public javax.swing.JLabel lblNomeStatus;
    public javax.swing.JLabel lblNumero;
    public javax.swing.JLabel lblQdtExcedente;
    public javax.swing.JLabel lblRazao;
    public javax.swing.JLabel lblRespnsavel;
    public javax.swing.JLabel lblRotaDescricao;
    public javax.swing.JLabel lblStatus;
    public javax.swing.JLabel lblTotal;
    public javax.swing.JLabel lblUF;
    public javax.swing.JLabel lblmodelo;
    public javax.swing.JLabel lblrotaID;
    public javax.swing.JTextField txtCodMotorista;
    public javax.swing.JTextField txtCodVeiculo;
    public javax.swing.JTextField txtMotorista;
    public javax.swing.JTextField txtObs;
    public javax.swing.JTextField txtQdtColetada;
    public javax.swing.JTextField txtQdtContratada;
    public javax.swing.JTextField txtValorExcedente;
    public javax.swing.JTextField txtVeiculo;
    public javax.swing.JTextField txtlValorFixo;
    private java.util.List<entity.Veiculo> veiculoList;
    private javax.persistence.Query veiculoQuery;
    // End of variables declaration//GEN-END:variables
    EntityManagerFactory emf;
    EntityManager em;
}
